name: ManagePrBranchMergeability

on:
    pull_request:
        types: [opened, edited, reopened, synchronize]
        branches: 
          - master
          - release
env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_WORKFLOW_ID: ${{ github.run_id }}
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  
jobs:
  Manage-Mergeability:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Extract branch name
        run: |
              echo "PR_Branch_Name=${{ github.head_ref }}" >> $GITHUB_ENV  
              echo 'Event name:' ${{ github.event_name }}
     
      - name: Validate PR Title
        if: github.event_name == 'pull_request'
        run:  |
                echo PR Numer is: $GITHUB_PR_NUMBER
                
                restApiPRTitle=$(curl \
                                      -H "Accept: application/vnd.github.v3+json" \
                                      https://api.github.com/repos/naregkar/$GITHUB_REPOSITORY_NAME/pulls/$GITHUB_PR_NUMBER | jq  -r '.title')
                
                echo $restApiPRTitle
                
                if [[ $restApiPRTitle =~ ^\[DT-[0-9]+\] ]]; then
                  #if the title matches the pattern
                  echo 'PR Title is in correct format.'
                  
                  jira_IdUnparsed=$restApiPRTitle
                  jira_id=${jira_IdUnparsed%]*}
                  jira_id=${jira_id:1}
                  echo "JiraId=$jira_id" >> $GITHUB_ENV
                  
                else
                  echo 'PR Title does not comply with the required pattern.'                  
                  exit 1
                fi
                     
      
      - name: Read Issue details from Jira's API
        if: github.event_name == 'pull_request'
        run : |
               restApiGETJiraIssueDetails=$(curl --request GET \
                  --url 'https://naregkar.atlassian.net/rest/api/3/issue/${{ env.JiraId }}/' \
                  --user 'nareg.karamanoukian@picsart.com:oBJTrxuI3qf0Do1MBpGbBE87' \
                  --header 'Accept: application/json');        
               
               jira_Issue_Type=$(echo $restApiGETJiraIssueDetails | jq -r '.fields.issuetype.name')
               jira_PR_Version=$(echo $restApiGETJiraIssueDetails | jq -r '.fields.fixVersions[].name')
               
               echo "JiraIssueType=$jira_Issue_Type" >> $GITHUB_ENV
               echo "JiraPRVersion=$jira_PR_Version" >> $GITHUB_ENV
               
               if [[ "$jira_Issue_Type" == "Story" ]] || [[ "$jira_Issue_Type" == "Bug" ]] || [[ "$jira_Issue_Type" == "Task" ]]; then                
                    jira_Issue_Status=$(echo $restApiGETJiraIssueDetails | jq -r '.fields.status.name')
               else
                    jira_Issue_Status=$(echo $restApiGETJiraIssueDetails | jq -r '.fields.parent.fields.status.name')
               fi
               
               echo "JiraStatus=$jira_Issue_Status" >> $GITHUB_ENV               
               
              
      - name: Read the version file from the master branch
        if: github.event_name == 'pull_request'
        run : |
               contentMaster=$(curl \
                               -H "Accept: application/vnd.github.v3+json" \
                               https://api.github.com/repos/naregkar/$GITHUB_REPOSITORY_NAME/contents/.github/version | jq -r '.content')
                                       
               echo "MasterVersion=$(echo $contentMaster | base64 -d)" >> $GITHUB_ENV
             
             
      - name: Compare values and assess the mergeability based on the version files
        if: github.event_name == 'pull_request'
        run: |
              echo 'pr version is:' $JiraPRVersion
              echo 'master version is:' $MasterVersion
              
              if [[ "$JiraPRVersion" == "$MasterVersion" ]]; then
                echo 'Matching PR and master versions.'
              else
                echo 'PR branch planned for a future release. Cannot merge now.'
                exit 1
              fi
      
      - name: Save GitHub info in Jira Issue item
        if: github.event_name == 'pull_request'
        run: |
                echo 'issue type is:' $issue_type
              
                #save the repo name and GitHub workflow id
                curl -D- -u nareg.karamanoukian@picsart.com:oBJTrxuI3qf0Do1MBpGbBE87 \
                    -X PUT --data '{ "fields": { "customfield_10033" : "'"$GITHUB_REPOSITORY_NAME"'", "customfield_10029" : "'"$GITHUB_WORKFLOW_ID"'"  }}' \
                    -H "Content-Type: application/json" https://naregkar.atlassian.net/rest/api/3/issue/${{ env.JiraId }}
      
      
      - name: Assess the Jira Status
        if: github.event_name == 'pull_request'
        run: |
               echo 'status:' ${{ env.JiraStatus }}
               
               curl -D- -u nareg.karamanoukian@picsart.com:oBJTrxuI3qf0Do1MBpGbBE87 \
                   -X PUT --data '{ "fields": { "customfield_10029" : "'"$GITHUB_WORKFLOW_ID"'" }}' \
                   -H "Content-Type: application/json" https://naregkar.atlassian.net/rest/api/3/issue/${{ env.JiraId }}
               
               toMergeStatus="Ready to Merge"
               
               if [[ "${{ env.JiraStatus }}" == "$toMergeStatus" ]]; then
                 echo "PR can be merged to master."
               else
                 echo "Jira Issue's status is not Ready to Merge. Cannot Merge to master."
                 exit 1
               fi
