name: ManageIssueType

on:
    pull_request:
        types: [opened, edited, reopened, synchronize]
env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  GITHUB_WORKFLOW_ID: ${{github.run_id}}
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  
jobs:
  Manage-IssueType:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Extract branch name
        run: |
              echo "PR_Branch_Name=${{ github.head_ref }}" >> $GITHUB_ENV  
              echo 'Event name:' ${{ github.event_name }}
      
      
      - name: Validate PR Title
        id: validatePRTitle
        if: github.event_name == 'pull_request'
        run:  |
                echo PR Numer is: $GITHUB_PR_NUMBER
                
                restApiPRTitle=$(curl \
                                      -H "Accept: application/vnd.github.v3+json" \
                                      https://api.github.com/repos/naregkar/devAutoMerge/pulls/$GITHUB_PR_NUMBER | jq  -r '.title')
                
                echo $restApiPRTitle
                
                if [[ $restApiPRTitle =~ ^\[DT-[0-9]+\] ]]; then
                  #if the title matches the pattern
                  echo 'PR Title is in correct format.'
                  
                  jira_IdUnparsed=$restApiPRTitle
                  jira_id=${jira_IdUnparsed%]*}
                  jira_id=${jira_id:1}
                  echo "JiraId=$jira_id" >> $GITHUB_ENV
                  
                else
                  echo 'PR Title does not comply with the required pattern.'                  
                  exit 1
                fi
      
      
      - name: Read Issue Type from Jira
        if: github.event_name == 'pull_request'
        run : |
               restApiGET=$(curl --request GET \
                  --url 'https://naregkar.atlassian.net/rest/api/3/issue/${{ env.JiraId }}/' \
                  --user 'nareg.karamanoukian@picsart.com:oBJTrxuI3qf0Do1MBpGbBE87' \
                  --header 'Accept: application/json' | jq -r '.fields.issuetype.name');                   
              
               echo "issue_type=$restApiGET" >> $GITHUB_ENV           
          
          
      - name: Save GitHub info in Jira Issue item
        if: github.event_name == 'pull_request'
        run: |
                echo 'issue type is:' $issue_type
              
                #save the repo name and GitHub workflow id
                curl -D- -u nareg.karamanoukian@picsart.com:oBJTrxuI3qf0Do1MBpGbBE87 \
                    -X PUT --data '{ "fields": { "customfield_10033" : "'"$GITHUB_REPOSITORY_NAME"'", "customfield_10029" : "'"$GITHUB_WORKFLOW_ID"'"  }}' \
                    -H "Content-Type: application/json" https://naregkar.atlassian.net/rest/api/3/issue/${{ env.JiraId }}
        
        
      - name: Assess Jira Status
        run: |
                if [[ "$issue_type" == "Story" ]] || [[ "$issue_type" == "Bug" ]] || [[ "$issue_type" == "Task" ]]; then
                    echo 'Story or bug or task.'
                    
                    curl -D- -u nareg.karamanoukian@picsart.com:oBJTrxuI3qf0Do1MBpGbBE87 \
                        -X PUT --data '{ "fields": { "customfield_10029" : "'"$GITHUB_WORKFLOW_ID"'" }}' \
                        -H "Content-Type: application/json" https://naregkar.atlassian.net/rest/api/3/issue/${{ env.JiraId }}
               
                    toMergeStatus="Ready to Merge"
               
                    if [[ "${{ env.JiraIssue_Status }}" == "$toMergeStatus" ]]; then
                        echo "PR can be merged to master"
                    else
                        echo "Jira Issue's status is not Ready to Merge. Cannot Merge to master."
                    exit 1
                    fi
                    
                else
                    echo 'The Issue is a sub-task.'
                    
                    restApiGETParentStatus=$(curl --request GET \
                        --url 'https://naregkar.atlassian.net/rest/api/3/issue/${{ env.JiraId }}/' \
                        --user 'nareg.karamanoukian@picsart.com:oBJTrxuI3qf0Do1MBpGbBE87' \
                        --header 'Accept: application/json' | jq -r '.fields.parent.fields.status.name')
                        
                        toMergeStatus="Ready to Merge"
                        echo $restApiGETParentStatus
               
                    if [[ "$restApiGETParentStatus" == "$toMergeStatus" ]]; then
                        echo "PR can be merged to master"
                    else
                        echo "Issue's parent status is not Ready to Merge. Cannot Merge to master."
                        exit 1
                    fi
                        
                fi                   
      
