name: Manage 2 PR 2 Code 2 Reviewers 2

on:
  pull_request_review:
    types: [submitted] 
env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  
jobs:
  Manage-2-PR-2-Reviewers-2:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Retrieve PR Title
        run:  |
                restApiPRTitle=$(curl \
                                      -H "Accept: application/vnd.github.v3+json" \
                                      -H 'authorization: token ${{ secrets.TOKEN_GITHUB }}' \
                                      https://api.github.com/repos/naregkar/$GITHUB_REPOSITORY_NAME/pulls/$GITHUB_PR_NUMBER | jq  -r '.title')
                
                echo "prTitlefromAPI=$restApiPRTitle" >> $GITHUB_ENV
      
      - name: Login to JIRA
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      
      - name: Find Jira Issue Id in commit messages
        id: find
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: "${{ env.prTitlefromAPI }}" #${{ github.head_ref }} ${{ github.event.head_commit.message }}"
          from: "" 
          
      - name: Add label for the PR
        if: steps.find.outputs.issue == ''
        run: |
              curl \
                    -X POST \
                    -H "Accept: application/vnd.github.v3+json" \
                    -H 'authorization: token ${{ secrets.TOKEN_GITHUB }}' \
                    -d '["ReviwerWorkflowId:${{ github.run_id }}"]' \
                    https://api.github.com/repos/naregkar/devAutoMerge/issues/$GITHUB_PR_NUMBER/labels;
      
      - name: Remove re-run label
        if: steps.find.outputs.issue != ''
        run: |
              restApiGetLabels=$(curl \
                                -H "Accept: application/vnd.github.v3+json" \
                                -H 'authorization: token ${{ secrets.TOKEN_GITHUB }}' \
                                https://api.github.com/repos/naregkar/devAutoMerge/issues/$GITHUB_PR_NUMBER/labels)
                                
               labelNameExtracted=$(echo $restApiGetLabels | jq -r '.[] | select(.name | contains("ReviwerWorkflowId")) | .name');           
               
               curl \
                  -X DELETE \
                  -H "Accept: application/vnd.github.v3+json" \
                  -H 'authorization: token ${{ secrets.TOKEN_GITHUB }}' \
                  https://api.github.com/repos/naregkar/devAutoMerge/issues/$GITHUB_PR_NUMBER/labels/$labelNameExtracted
      
      - name: Check if Jira issue Status is 'Code Review'
        if: steps.find.outputs.issue != ''
        run: |
              restApiGETJiraIssueDetails=$(curl --request GET \
                  --url '${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.find.outputs.issue }}/' \
                  --user '${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}' \
                  --header 'Accept: application/json');
                  
              jira_Issue_Status=$(echo $restApiGETJiraIssueDetails | jq -r '.fields.status.name')
              
              jira_Issue_Type=$(echo $restApiGETJiraIssueDetails | jq -r '.fields.issuetype.name')
              echo "JiraIssueType=$jira_Issue_Type" >> $GITHUB_ENV

              
              if [[ ${jira_Issue_Status} != "Code Review" ]]; then
                echo 'The Jira status is' $jira_Issue_Status 'for Issue: if: steps.find.outputs.issue != ''. Cannot proceed when the status is not set to Code Review.'
                exit 1
              fi                         
      
      - name: Assess the PR Reviewers Count
        if: steps.find.outputs.issue != ''
        run:  |
                
                restApiGETGitHubReviewersDetails=$(curl \
                            -H "Accept: application/vnd.github.v3+json" \
                            -H 'authorization: token ${{ secrets.TOKEN_GITHUB }}' \
                            https://api.github.com/repos/naregkar/$GITHUB_REPOSITORY_NAME/pulls/$GITHUB_PR_NUMBER/reviews);
                  
                approverCount=$(echo $restApiGETGitHubReviewersDetails | jq 'group_by(.user.login) | map(select(max_by(.submitted_at) .state == "APPROVED")) | length')
                
                echo 'Number of approved reviewers:' $approverCount
                
                if [[ "$approverCount" -lt 1 ]]; then
                    echo 'More reviewers are needed in order for this Jira item to progress within its workflow.'
                    exit 1
                else
                    echo 'Minimum number of code reviewers passed. Change assignee and status.'
                    
                    echo "CodeReviewDone=true" >> $GITHUB_ENV
                    
                    #assign Jira Issue to a certain person/unassign depends on the team
                    curl --request PUT \
                      --url '${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.find.outputs.issue }}/assignee' \
                      --user '${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}' \
                      --header 'Accept: application/json' \
                      --header 'Content-Type: application/json' \
                      --data '{
                      "accountId": "5fea9ba3dd5eb5010881866b"
                    }'
                    
                    #Change the Jira issue Status to QA Open
                    curl -D- -u ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
                      -X POST --data '{"transition":{"id":"61"}}' \
                      -H "Content-Type: application/json" ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.find.outputs.issue }}/transitions
         
                fi
                
                
      - name: Jenkins Job
        if: github.event.pull_request.base.ref == 'master' && env.CodeReviewDone == 'true' && steps.find.outputs.issue != ''
        run: |
                echo 'heyyyyyy'
                echo 'env: ' ${{ env.CodeReviewDone }}
