name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review, synchronize]
    branches:
    - master
    - release
    - live
env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  
jobs:
  Validate-PR-Title:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Read the list of admins from the admin file
        if: github.event_name == 'pull_request'
        run : |
               contentAdmins=$(curl \
                               -H "Accept: application/vnd.github.v3+json" \
                               https://api.github.com/repos/naregkar/$GITHUB_REPOSITORY_NAME/contents/.github/ADMINS | jq -r '.content')
               
               someArray=$(echo $contentAdmins | base64 -d)
               
               read -a myarray <<< $someArray

               echo "My array: ${myarray[@]}"
               echo "Number of elements in the array: ${#myarray[@]}"
               
               if [[ " ${myarray[*]} " == *" naregkar1234 "* ]]; then
                 echo "myarray contains naregkar"
               fi
             
               

               #echo "ListOfAdmins=$(echo $contentAdmins | base64 -d)" >> $GITHUB_ENV
               
      - name: Extract Jira Issue Key
        if: github.event.pull_request.draft == false
        run:  |
                echo PR Numer is: $GITHUB_PR_NUMBER
                
                ehco 'list: ' ${{ env.ListOfAdmins }}
                
                restApiPRTitle=$(curl \
                                      -H "Accept: application/vnd.github.v3+json" \
                                      -H 'authorization: token ${{ secrets.TOKEN_GITHUB }}' \
                                      https://api.github.com/repos/naregkar/$GITHUB_REPOSITORY_NAME/pulls/$GITHUB_PR_NUMBER | jq  -r '.title')
                
                echo 'Entered title is:' $restApiPRTitle
                
                if [[ $restApiPRTitle =~ ^\[DT-[0-9]+\] ]]; then
                  #if the title matches the required pattern
                  
                  jira_IdUnparsed=$restApiPRTitle
                  jira_id=${jira_IdUnparsed%]*}
                  jira_id=${jira_id:1}
                  echo "JiraId=$jira_id" >> $GITHUB_ENV
                  
                else
                  echo 'PR Title does not comply with the required pattern - [PW-xxxx]'
                  
                  echo 'list:' ${{ env.JiraId }}
                  
                fi
