name: ValidateTitle

on:
  pull_request:
    types: [edited]
env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  GITHUB_WORKFLOW_ID: ${{github.run_id}}
  
jobs:
  Validate-Title:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Extract branch name
        if: github.event_name == 'pull_request'
        run: |
              echo 'Event name:' ${{ github.event_name }}
